packaging_format = 2

id = "monica"
name = "Monica"
description.en = "Personal Relationship Manager"
description.fr = "Gestionnaire de relations personnelles"

version = "v5.0.0-beta.2~ynh1"

maintainers = ["Sebastian Gumprich"]

[upstream]
license = "GPL-3.0"
website = "https://monicahq.com"
code = "https://github.com/monicahq/monica"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap =  false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/monica"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["cs", "de", "en", "es", "fr", "he", "it", "nl", "pt", "ru", "zh"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/monicahq/monica/archive/refs/tags/v5.0.0-beta.2.zip"
        sha256 = "62f1f8df345632003563f22fce828c12c98be7918badb8997833b2579b40b043"
        autoupdate.strategy = "latest_github_tag"
        
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.1-bcmath php8.1-cli php8.1-curl php8.1-dom php8.1-gd php8.1-gmp php8.1-iconv php8.1-intl php8.1-mbstring php8.1-mysql php8.1-mysqli php8.1-opcache php8.1-redis php8.1-xml php8.1-zip"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "mysql"
