packaging_format = 2

id = "monica"
name = "Monica"
description.en = "Personal Relationship Manager"
description.fr = "Gestionnaire de relations personnelles"

version = "5.0.0-beta.2~ynh1"

maintainers = ["Sebastian Gumprich"]

[upstream]
license = "GPL-3.0"
website = "https://monicahq.com"
code = "https://github.com/monicahq/monica"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap =  false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/monica"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["cs", "de", "en", "es", "fr", "he", "it", "nl", "pt", "ru", "zh"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/monicahq/monica/archive/refs/tags/v5.0.0-beta.2.tar.gz"
        sha256 = "bce9d1e0368d2efafc695e60a70b6c3bad10d7df2d519e2ec6d51daee666a0b1"
        autoupdate.strategy = "latest_github_tag"
        
        
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-bcmath, php8.2-cli php8.2-curl, php8.2-dom php8.2-gd, php8.2-gmp, php8.2-iconv php8.2-intl, php8.2-mbstring, php8.2-mysql, php8.2-mysqli php8.2-opcache, php8.2-redis, php8.2-xml, php8.2-zip"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "mysql"
